### ISSUE TITLE
Fail to build example due to missing xtensa-lx-rt

### ISSUE THREAD

**Issue by kadler** [esp-rs/esp8266-hal#12]
Followed the guide in the README and failed here:

```
 cargo +xtensa espflash --release --example blinky --tool cargo /dev/ttyUSB0 
    Updating crates.io index
error: failed to get `xtensa-lx-rt` as a dependency of package `esp8266-hal v0.4.0 (/home/zeke/repos/esp8266-hal)`

Caused by:
  failed to load source for dependency `xtensa-lx-rt`

Caused by:
  Unable to update /home/zeke/repos/xtensa-lx6-rt

Caused by:
  failed to read `/home/zeke/repos/xtensa-lx6-rt/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Seems to be caused by https://github.com/esp-rs/esp8266-hal/blob/master/Cargo.toml#L16 from https://github.com/esp-rs/esp8266-hal/commit/89c8319a8adbdefdfc7c6f8a9347d5baa087ac2d

Was this an errant change while testing some local configuration updating xtensa-lx-rt? Or does the readme need to be updated to clone https://github.com/esp-rs/xtensa-lx-rt ?

FYI I did manage to get things working by removing the path argument from Cargo.toml.

**Comment by icewind1991** [comment]
Fixed.

> Was this an errant change while testing

Correct
