### ISSUE TITLE
xargo build fails 

### ISSUE THREAD

**Issue by zinahe** [esp-rs/esp8266-hal#2]
Hi, thanks for your effort. 

I get this error:
```
error[E0463]: can't find crate for `std`
error: could not compile `semver-parser`.
```

It seems to be caused by this dependency chain.

`esp8266-hal -> esp8266 -> bare-metal -> rustc-version -> semver-parser`

and semver-parser requires `std`.

Please help.

Thanks.

**Comment by jessebraham** [comment]
This crate now builds using the unstable `build-std` feature from Cargo, so `xargo` is no longer required. You can read more about this feature [here](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std).

Assuming you have installed the [esp-rs Rust fork](https://github.com/esp-rs/rust) then you should be able to  just use `cargo build` within this project as expected.
